### ISSUE TITLE
Title: I wish to add about Simple Input and Output in the Python Documentation 

### ISSUE THREAD

**Issue by Iamchandra-3** [WeBeginners-Community/DocBook#109]
### Explain what you want to add/change in documentation.

There is no section in the python documentation about Input and Output ...
So I want to add that section which is a very basic and important one.

**Comment by sitamgithub-MSIT** [comment]
@Sulagna-Dutta-Roy Can you assign me this will contribute different input that commonly taken in coding problems in python.

**Comment by Sulagna-Dutta-Roy** [comment]
Coding files not needed. Also I've assigned you the same Issue for this one. 
Documentation needed only
