### ISSUE TITLE
Title: HTML Documentation

### ISSUE THREAD

**Issue by sumitkr2000** [WeBeginners-Community/DocBook#116]
### Is your feature request related to a problem? Please describe.

Hey, @Sulagna-Dutta-Roy I want to add HTML Documentation. Please assign me this issue. Thank you!

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

**Comment by sumitkr2000** [comment]
Pleas assign me this issue @Sulagna-Dutta-Roy

**Comment by sumitkr2000** [comment]
Pleas assign me this issue @Sulagna-Dutta-Roy

**Comment by himanshubalani** [comment]
@sumitkr2000  I'm also doing HTML Documentation. Check Out #101 to know what I'm working on and perhaps we can collaborate to avoid conflicts

**Comment by sumitkr2000** [comment]
@himanshubalani I am adding basics of HTML in the documentation

**Comment by sumitkr2000** [comment]
If you are working on it...I can open another issue

**Comment by himanshubalani** [comment]
@sumitkr2000  Yes, I am working on adding Style Tag, HTML Tables, HTML Lists, Div Element, Span Element right now.
Feel free to add other elements and tags. There's a lot of HTML for both of us :)

**Comment by sumitkr2000** [comment]
ok I will add more HTML tags and other important concepts
