### ISSUE TITLE
accident prevention system

### ISSUE THREAD

**Issue by Disha2004Verma** [WeBeginners-Community/DocBook#12]
### Is your proposal related to a problem? Please describe.

Continuous advancements in computing technology and artificial intelligence in the past decade have
led to improvements in driver monitoring systems. Numerous experimental studies have collected
real driver drowsiness data and applied various artificial intelligence algorithms and feature
combinations with the goal of significantly enhancing the performance of these systems in real-time.
Driver sleep detection is a car safety technology which helps to prevent accidents when the driver
gets drowsy. Various studies have suggested that around 20% of road accidents are fatigue related. A
sleep alarm is used in a vehicle for detecting the condition indicative of the onset of sleepiness of a
driver and for alerting the driver. The proposed system aims to lessen the number of accidents that
occur due to drivers’ drowsiness and fatigue, which will in turn increase transportation safety. This
is becoming a common reason for accidents in recent times. Several faces and body gestures are
considered such as signs of drowsiness and fatigue in drivers, including tiredness in eyes and
yawning.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting any projects. If you want to add anything then make sure it will be a documentation in particular topics. Check my repository as well
