### ISSUE TITLE
Title: C++ Standard Template Library Basics Documentation

### ISSUE THREAD

**Issue by silentspectator20** [WeBeginners-Community/DocBook#127]
### Explain what you want to add/change in documentation.

I want to add the basics of Standard Template Library Containers like vectors, lists, maps, stack, queues, etc.

Kindly please assign me this issue.

Regards

**Comment by Sulagna-Dutta-Roy** [comment]
Only one topic documentation please.

**Comment by silentspectator20** [comment]
@Sulagna-Dutta-Roy  I would like to add documentation of maps where I will explain unordered maps and ordered maps.
Please assign me this issue.

**Comment by silentspectator20** [comment]
@Sulagna-Dutta-Roy Kindly please review the PR and Merge it. Any suggestions are welcomed. Thank you!
