### ISSUE TITLE
Title: Sum of subset problem

### ISSUE THREAD

**Issue by Amit0412** [WeBeginners-Community/DocBook#162]
### Is your feature request related to a problem? Please describe.

I would like to mention about this classic problem based on backtracking.

### Describe the solution you'd like.

Will explain about backtracking+ problem statement+ code 

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

na

**Comment by nerdy-nakul** [comment]
Hello @Sulagna-Dutta-Roy,
Is this issue still opne, may i contribute ?

**Comment by Sulagna-Dutta-Roy** [comment]
@Amit0412 Hi, are you still working on this?

**Comment by Amit0412** [comment]
@Sulagna-Dutta-Roy No I am not working on this issue.
