### ISSUE TITLE
Title: Kadane Algorithm to calculate maximum subarray

### ISSUE THREAD

**Issue by Vanraj8169** [WeBeginners-Community/DocBook#170]
### Is your feature request related to a problem? Please describe.

Kadane's Algorithm is an iterative dynamic programming algorithm. It calculates the maximum sum subarray ending at a particular position by using the maximum sum subarray ending at the previous position.

### Describe the solution you'd like.

The idea of Kadane’s algorithm is to maintain a variable max_ending_here that stores the maximum sum contiguous subarray ending at current index and a variable max_so_far stores the maximum sum of contiguous subarray found so far, Everytime there is a positive-sum value in max_ending_here compare it with max_so_far and update max_so_far if it is greater than max_so_far.

### Describe alternatives you've considered.

No

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/87256781/214821167-d4870c57-78ae-4479-9d96-1af100413697.png)

**Comment by sitamgithub-MSIT** [comment]
@Sulagna-Dutta-Roy Can you assign me this in python?
