### ISSUE TITLE
Title: C++ Exception Handling

### ISSUE THREAD

**Issue by Gaurav-8604** [WeBeginners-Community/DocBook#178]
### Explain what you want to add/change in documentation.

Add a documentation about C++ Exception handling

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists this project in the repo

**Comment by Gaurav-8604** [comment]
OK! No Problem.

**Comment by Gaurav-8604** [comment]
@Sulagna-Dutta-Roy  What about Exception handling

**Comment by Sulagna-Dutta-Roy** [comment]
??

**Comment by Gaurav-8604** [comment]
Handling exceptions in C++, try catch block and default exceptions like DivideByZero, etc

**Comment by Gaurav-8604** [comment]
> Handling exceptions in C++, try catch block and default exceptions like DivideByZero, etc

@Sulagna-Dutta-Roy ?

**Comment by Sulagna-Dutta-Roy** [comment]
Go for it

**Comment by Gaurav-8604** [comment]
@Sulagna-Dutta-Roy Please check.
All of your requirements have been met by me.
Thankyou!
