### ISSUE TITLE
COVID Detection Tool

### ISSUE THREAD

**Issue by Amit0412** [WeBeginners-Community/DocBook#228]
### Is your feature request related to a problem? Please describe.

This tool is designed for two kinds of user. One with Chest X-Ray scan reports and others without that.
For users with Chest X-Ray scan, we developed a Machine Learning Algorithm using Convolutional Neural Network to detect whether the user suffers from COVID or not. User needs to input his/her chest x-ray scan in the python application as input and a dialogue box appears as the output.
For users without chest x-ray scan, we built a website that takes symptoms from the user and based upon those symptoms, the tool detects the probability of user suffering from COVID and provides them with necessary further steps and diet charts.

### Describe the solution you'd like.

For Chest X-Ray scan based application: Python, ML, Tensorflow, CNN, WX
For Symptoms based website: HTML, SCSS, BootStrap, JavaScript

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

**Comment by Sulagna-Dutta-Roy** [comment]
No projects accepted. It's a documentation repository
