### ISSUE TITLE
Title: Typescript Docs

### ISSUE THREAD

**Issue by Nidhish-07** [WeBeginners-Community/DocBook#239]
### Explain what you want to add/change in documentation.

@Sulagna-Dutta-Roy I would like to add the documentation of typescript. Please assign me this issue. Thank you!

A very important language for development.

**Comment by Ujwal19k** [comment]
Hello @Nidhish-07 can I cover the loops, conditional and switch statement in TypeScript ? I'll make a new issue. Is it ok @Sulagna-Dutta-Roy ?

**Comment by Nidhish-07** [comment]
> 

OK
