### ISSUE TITLE
Cyclic Sort

### ISSUE THREAD

**Issue by bmpskvas** [WeBeginners-Community/DocBook#24]
### Is your proposal related to a problem? Please describe.

I would like to add the algorithm of cyclic sort to the repo.
Kindly assign me the task.

**Comment by Apoorvakothari** [comment]
@Sulagna-Dutta-Roy can you please assign this issue to me?

**Comment by Sulagna-Dutta-Roy** [comment]
@khushi41bansal If you're working this Issue then let me know? 
Otherwise will assign to another

**Comment by khushi41bansal** [comment]
Yes mam i am making up the repo..it will be completed by 20th jan.
Actually i have my exaslms till 19th.
Will do after that

**Comment by sitamgithub-MSIT** [comment]
@Sulagna-Dutta-Roy If the work still not done, please assign me that
