### ISSUE TITLE
Title: Typescript Doc (loops, conditional and switch statement)

### ISSUE THREAD

**Issue by Ujwal19k** [WeBeginners-Community/DocBook#242]
### Explain what you want to add/change in documentation.

@Sulagna-Dutta-Roy I would like to add Loops, Conditional Statements and Switch statement in the documentation of typescript. 
@Nidhish-07 is working on other documentation part and he has no problem on me working on this. Please assign me this as a part of SWOC 2023. Thank you !

**Comment by Sulagna-Dutta-Roy** [comment]
Mention the Issue no

**Comment by Ujwal19k** [comment]
Issue no: #239 
Issued by: @Nidhish-07
