### ISSUE TITLE
Title: To Add Cpp STL "Functors" concept

### ISSUE THREAD

**Issue by Kshitij321** [WeBeginners-Community/DocBook#246]
### Explain what you want to add/change in documentation.

I want to add "FUNCTORS" Concept of Cpp STL in Cpp folder

**Comment by Sulagna-Dutta-Roy** [comment]
I think this project is already completed

**Comment by Sulagna-Dutta-Roy** [comment]
https://github.com/WeBeginners-Community/DocBook/issues/241#issue-1599592122 
The problem is it has the same thing in different topics. It will be hectic to track for you 😄 otherwise why didn't you added this topics before?
