### ISSUE TITLE
Title: Cycle Sort Algorithm

### ISSUE THREAD

**Issue by sumitkr2000** [WeBeginners-Community/DocBook#265]
### Is your proposal related to a problem? Please describe.

Hey, @Sulagna-Dutta-Roy I want to add the documentation of the cycle sort algorithm. Please assign me this issue. Thank you!

**Comment by sumitkr2000** [comment]
@Sulagna-Dutta-Roy Please assign me this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
Make sure no more Issues. Because today is the last day 🙏

**Comment by sumitkr2000** [comment]
Ok.
