### ISSUE TITLE
GCD and LCM Using Recursion

### ISSUE THREAD

**Issue by Shubh08am** [WeBeginners-Community/DocBook#37]
### Is your feature request related to a problem? Please describe.

We are given two numbers. We need to find there greatest common divisor (GCD) and least common divisor (LCM).

### Describe the solution you'd like.

Using Recursion to find greatest common divisor (GCD) and least common divisor (LCM) of given numbers.

### Describe alternatives you've considered.

Using Recursion in place of iterative process.

**Comment by Sulagna-Dutta-Roy** [comment]
Code snippets not needed. Because its documentation repository.also the PR merged correctly
