### ISSUE TITLE
Title: doc for heap sort

### ISSUE THREAD

**Issue by shubham0730** [WeBeginners-Community/DocBook#45]
### Is your proposal related to a problem? Please describe.

Documentation for heap sort in algorithm section

**Comment by shubham0730** [comment]
please assign this issue to me under swoc

**Comment by shubham0730** [comment]
Someone seems to have added the doc for heap sort. Should I add code in the doc?

**Comment by Sulagna-Dutta-Roy** [comment]
Yess add the code
