### ISSUE TITLE
sieve of Eratosthenes Algorithm

### ISSUE THREAD

**Issue by Shubh08am** [WeBeginners-Community/DocBook#48]
### Is your feature request related to a problem? Please describe.

I would like to add sieve of Eratosthenes Algorithm which is the most efficient ways to find all primes .

### Describe the solution you'd like.

Using, concept of factors , hashing to print prime numbers.

### Describe alternatives you've considered.

We can use frequency vector in place of hashing.

**Comment by sitamgithub-MSIT** [comment]
@Sulagna-Dutta-Roy Can you assign me the work will be implementing in python.
