### ISSUE TITLE
Add Tower of Hanoi Algorithm

### ISSUE THREAD

**Issue by dineshnalam** [WeBeginners-Community/DocBook#76]
Tower of Hanoi is a mathematical puzzle where we have three rods and n disks, the objective of the puzzle is to move the entire stack to another rod with following conditions:
- Only one disk can be moved at a time.
-  No disk may be placed on top of a smaller disk.
- Each move consists of taking the upper disk from one of the stacks. 

Please assign this to me @Sulagna-Dutta-Roy

**Comment by sitamgithub-MSIT** [comment]
@Sulagna-Dutta-Roy Please assign me this will do in python.
