### ISSUE TITLE
Reverse of a string using recursion in C++

### ISSUE THREAD

**Issue by SparklinStar** [WeBeginners-Community/DocBook#83]
### Is your proposal related to a problem? Please describe.

Please assign me this issue.

**Comment by silentspectator20** [comment]
Kindly please assign me this issue. I would be happy to contribute to it

**Comment by Sulagna-Dutta-Roy** [comment]
@SparklinStar Hello,are you working on this Issue?

**Comment by SparklinStar** [comment]
@Sulagna-Dutta-Roy Yes, I want to work here, but until now you have not assigned me this issue.
